### ISSUE TITLE
jpgs_to_h5 is too slow

### ISSUE THREAD

**Issue by laohumultimedia** [pietz/language-recognition#3]
da.to_hdf5 is very very slow on my machine, have you faced the issue?

**Comment by pietz** [comment]
Yes, it can be. In this step the entire data is loaded into memory,
preprocessed and written back to disk. Depending on the size of your
dataset this can take a few minutes. Understand that when working with dask
arrays many steps are executed instantly because the actual work is not
being done "yet".
