### ISSUE TITLE
Converted image is not similar to the sample. And accuracy is under 0.6%

### ISSUE THREAD

**Issue by nagataaaas** [pietz/language-recognition#5]
I converted the mp3 to img.
And I got jpg like this
![0a0p10uya0h mp3](https://user-images.githubusercontent.com/32694778/45603327-24b3e500-ba66-11e8-87f4-90f194c440c8.jpg)
But sample is this
![0a0p10uya0h mp3](https://user-images.githubusercontent.com/32694778/45603331-2da4b680-ba66-11e8-85a5-2ce35ac1bf14.jpg)
Those are totally different.

And the acc of predict and evaluate is under 0.7% (around 1/176) If I do that with the model both I trained and pietz trained.
acc during fit is also.

How can I solve that.
thx. and sorry for my poor English

**Comment by pietz** [comment]
Something is wrong with your conversion of the mp3 files to spectrograms.
It's hard to tell what exactly based on the information you provide.

If your spectrogram values go from 0 to 1 you can try to take the square
root of each value. That way it will be distributed more towards the 1-end
e.g. it will lift the values that are currently dark.

If my trained model leads to bad performance, it further indicates that
your preprocessing if not the same as mine. I believe some APIs changed in
librosa since I shared my solution. That may be a possible problem.

**Comment by nagataaaas** [comment]
Thank you for your advice.

I downgraded librosa from 0.6.2 to 0.5.0 and the converted image is now like sample!!
Maybe the API has changed.

I don't know how the acc will change( because now I'm converting the mp3 ). But I think this will work!!

Thank you.

**Comment by pietz** [comment]
Great! Thanks for reporting back.

When I find time in the future, I'll update the code to work with the recent version.
